### ISSUE TITLE
Make your JS more efficient

### ISSUE THREAD

**Issue by davisdude** [cwclaib/cwclaib.github.io#2]
Very minor, but here:

https://github.com/cwclaib/cwclaib.github.io/blob/c6e9ec53de9e9e549daf18e2ce58b105bad446e8/football/scorigami/script.js#L118-L120

You should be able to replace this with something like:

```javascript
elem.classList = ["green"]
```

Another thing:

https://github.com/cwclaib/cwclaib.github.io/blob/c6e9ec53de9e9e549daf18e2ce58b105bad446e8/football/scorigami/script.js#L76

This is icky :nauseated_face: 

You should make a list of scores meeting this criteria, then use something like [this](https://stackoverflow.com/a/67200398/2238176) to check if the new pair is in the list. :slightly_smiling_face:

**Comment by cwclaib** [comment]
Brother I know line 76 icky but I tried so hard to make it nice and javascript simply wouldn't let me.  (Also one flag, it doesn't work if the numbers equal eachother and 1,1 is an impossible score, so ha!

**Comment by davisdude** [comment]
This has been fixed :slightly_smiling_face:
